### PR TITLE
Added max speed for 3.5eWHF

### PR DESCRIPTION
**Pull request by innominate227**
Added max speed for 3.5eWHF.

### CODE REVIEW

**Comment by quielb** [comment]
7 speeds doesn't seem correct to me. I don't recall them ever having a fan with a odd number of speeds. 
Also can you please bump the version number in __init__.py to 1.9.3

**Comment by innominate227** [comment]
Last page of this doc https://cdn.shopify.com/s/files/1/2256/6107/files/Archive_35e_44e_WHF_IOM_2014.pdf.
And I updated the version number

**Comment by quielb** [comment]
The documentation is a little mis-leading. They list 7 speeds, but only 6 of them are "on" speeds. The 7th speed is off. The speed list in const.py is for "on" speeds.

**Comment by innominate227** [comment]
No.  The speeds are 800/1300/1600/2050/2500/2900/3500 CFM.  If one of those 7 were off then it would be 0CFM.

**Comment by quielb** [comment]
You're right. I shouldn't have tried to read the doc on my phone

**Pull request merged**
